<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_sortItemPrice</name>
   <tag></tag>
   <elementGuidId>c9e46564-349a-41f9-abc4-8d170a06425f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_container']/div[2]/div/span/select/option[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='header_container']/div[2]/div/span/select/option[1]</value>
      <webElementGuid>11fe8705-8592-4b2d-8d46-1cc8aee78229</webElementGuid>
   </webElementProperties>
</WebElementEntity>
